### ISSUE TITLE
🗄️ [Documentation] - Actual deployment with Nomad

### ISSUE THREAD

**Issue by DistroByte** [actualbudget/docs#17]
### Description

Actual is currently incompatible with Nomad for some file access reasons to do with the sqlite DB

```
Rejection: SqliteError: database is locked
    at sqliteTransaction (/app/node_modules/better-sqlite3/lib/methods/transaction.js:66:9)
    at WrappedDatabase.transaction (/app/db.js:29:35)
    at addMessages (/app/sync-simple.js:27:6)
    at Object.sync (/app/sync-simple.js:82:14)
    at /app/app-sync.js:114:42
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22 {
  code: 'SQLITE_BUSY'
}
```

Some form of official note that it is incompatible with Nomad would be great, testing mentioned in this message https://discord.com/channels/937901803608096828/969693280226906162/1031910347105390653

### Category

Installation & Configuration

**Comment by rich-howell** [comment]
Thanks for this @DistroByte I have merged a version of the Installation Overview into main which has some limitations within.
