### ISSUE TITLE
🐛 [BUG] - Cannot install Actual because it cannot locale bindings

### ISSUE THREAD

**Issue by jeremyfourna** [actualbudget/docs#171]
### Description

When I try to install actual server with actual on my local machine everything works until I run `yarn start`, then I get this error.

I only have this error with actual version 23.5.0, when I do `git checkout v23.4.2` then run `yarn install` and `yarn start` everything work.

```
/Users/perso/Projects/actual-server/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/compiled/20.1.0/darwin/x64/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/perso/Projects/actual-server/node_modules/better-sqlite3/lib/binding/node-v115-darwin-x64/better_sqlite3.node
    at bindings (/Users/perso/Projects/actual-server/node_modules/bindings/bindings.js:126:9)
    at new Database (/Users/perso/Projects/actual-server/node_modules/better-sqlite3/lib/database.js:48:64)
    at openDatabase (file:///Users/perso/Projects/actual-server/src/db.js:57:30)
    at getAccountDb (file:///Users/perso/Projects/actual-server/src/account-db.js:23:18)
    at SecretsDb.open (file:///Users/perso/Projects/actual-server/src/services/secrets-service.js:52:12)
    at SecretsDb.initialize (file:///Users/perso/Projects/actual-server/src/services/secrets-service.js:42:22)
    at new SecretsDb (file:///Users/perso/Projects/actual-server/src/services/secrets-service.js:21:10)
    at file:///Users/perso/Projects/actual-server/src/services/secrets-service.js:81:19
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25) {
  tries: [
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/compiled/20.1.0/darwin/x64/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/Users/perso/Projects/actual-server/node_modules/better-sqlite3/lib/binding/node-v115-darwin-x64/better_sqlite3.node'
  ]
}

Node.js v20.1.0
```

### Reproduction URL

http://localhost:5006

### Reproduction steps

```bash
1. Fresh install of actual v23.5.0
2. run `yarn start`
3. See error
```

**Comment by shall0pass** [comment]
I see you're using Node.js version 20.  All of the projects published docker builds still use Node.js version 16.  I believe it has something to do with the better-sqlite3 package support.  Try using version 16.

**Comment by j-f1** [comment]
If that doesn’t work, can you attach the output of running `yarn install` and `yarn rebuild`?

**Comment by jeremyfourna** [comment]
I changed my node version to `v16.20.0` and it works thanks. Could you check to add the node engine inside the `package.json`? https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

**Comment by j-f1** [comment]
Feel free to open a PR! That would be nice to have
